import json
import requests

API_URL = 'https://translate.googleapis.com/translate_a/single'
BATCH_SIZE = 25

manual_es = {
    "Add match": "Añadir partido",
    "Add players": "Añadir jugadores",
    "Add set points": "Añadir puntos del set",
    "Add competition": "Añadir competición",
    "Add": "Añadir",
    "Add player": "Añadir jugador",
    "Add players manually": "Añade jugadores manualmente",
    "Add points live": "Añadir puntos en directo",
    "Add user": "Añadir usuario",
    "Add a match manually by entering the players and the final score": "Añade un partido manualmente introduciendo a los jugadores y el marcador final",
    "Add players one by one by entering their nickname. (Irreversible).": "Añade a los jugadores uno a uno introduciendo su apodo. (Irreversible).",
    "Auto-updating": "Actualización automática",
    "Automatic rankings and schedules": "Clasificaciones y calendarios automáticos",
    "Best of": "Al mejor de",
    "Bracket": "Cuadro",
    "Cancel": "Cancelar",
    "Champion": "Campeón",
    "Close": "Cerrar",
    "Code copied to clipboard!": "¡Código copiado al portapapeles!",
    "Competition code": "Código de la competición",
    "Competition deleted successfully.": "Competición eliminada correctamente.",
    "Competition details": "Detalles de la competición",
    "Competition name": "Nombre de la competición",
    "Competitions": "Competiciones",
    "Continue": "Continuar",
    "Create": "Crear",
    "Create a competition": "Crear una competición",
    "Create a free account...": "Crea una cuenta gratuita...",
    "Create a new competition": "Crear una nueva competición",
    "Create a new competition to start recording matches, rankings, and statistics.": "Crea una nueva competición para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Create a new competition to start tracking matches, standings and stats.": "Crea una nueva competición para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Create free account": "Crear cuenta gratuita",
    "Create or join a competition": "Crea o únete a una competición",
    "Create your first competition": "Crea tu primera competición",
    "Create your tournament": "Crea tu torneo",
    "Created by": "Creada por",
    "Delete": "Eliminar",
    "Delete player": "Eliminar jugador",
    "Details": "Detalles",
    "Do you want to join the competition as a player?": "¿Quieres unirte a la competición como jugador?",
    "Edit": "Editar",
    "Edit competition": "Editar competición",
    "Edit players": "Editar jugadores",
    "Edit profile": "Editar perfil",
    "Edit your nickname": "Edita tu apodo",
    "Email is used to send match notifications directly to the player. Enter it to send tournament updates. You can also leave it blank.": "El correo electrónico se usa para enviar notificaciones de partidos directamente al jugador. Escríbelo para enviar actualizaciones del torneo. También puedes dejarlo en blanco.",
    "Elimination mode is under development: soon you will record matches and automatic advancements.": "El modo de eliminación está en desarrollo: pronto podrás registrar partidos y avances automáticos.",
    "English": "Inglés",
    "Enter your email": "Introduce tu correo electrónico",
    "Enter your password": "Introduce tu contraseña",
    "Free management": "Gestión libre",
    "Group": "Grupo",
    "Group stage": "Fase de grupos",
    "Here you can add multiple players at once, enter a nickname (and an optional photo) and click 'Add player' to add him.": "Aquí puedes añadir varios jugadores a la vez: introduce un apodo (y una foto opcional) y pulsa «Añadir jugador» para incorporarlo.",
    "Home": "Inicio",
    "Loading...": "Cargando...",
    "Log in": "Iniciar sesión",
    "Log in with Google": "Inicia sesión con Google",
    "Log Out": "Cerrar sesión",
    "No matches found, add one!": "No se encontraron partidos, ¡añade uno!",
    "No competitions yet. Create your first competition to start tracking matches, standings and stats.": "Aún no hay competiciones. Crea tu primera competición para empezar a registrar partidos, clasificaciones y estadísticas.",
    "No players yet. Add the first players to start tracking matches, standings and stats.": "Aún no hay jugadores. Añade a los primeros jugadores para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Or sign up": "O regístrate",
    "Profile": "Perfil",
    "Reset points": "Reiniciar puntos",
    "Save Match": "Guardar partido",
    "Save set": "Guardar set",
    "Search player": "Buscar jugador",
    "Select a player": "Selecciona un jugador",
    "Semifinals": "Semifinales",
    "Send access link by email": "Enviar enlace de acceso por correo",
    "Send access link to your friends via email to allow them to join the competition.": "Envía el enlace de acceso a tus amigos por correo electrónico para que puedan unirse a la competición.",
    "Invite your friends to join the competition via email.": "Invita a tus amigos a unirse a la competición por correo electrónico.",
    "Set a date": "Programar una fecha",
    "Sets (best of)": "Sets (al mejor de)",
    "Share the invitation code with your friends to allow them to join the competition and start recording matches, <br> click here to copy it to the clipboard.": "Comparte el código de invitación con tus amigos para permitirles unirse a la competición y empezar a registrar partidos. <br> Haz clic aquí para copiarlo al portapapeles.",
    "Share this code with your friends to allow them to join the competition.": "Comparte este código con tus amigos para permitirles unirse a la competición.",
    "Single elimination": "Eliminación directa",
    "Single elimination bracket, lose and you are out.": "Cuadro de eliminación directa: si pierdes quedas fuera.",
    "Some modes, like single elimination or group stage with knockout, require admin management. Go back and select Admin management to create them.": "Algunos modos, como la eliminación directa o la fase de grupos con eliminatoria, requieren la gestión del administrador. Vuelve atrás y selecciona Gestión del administrador para crearlos.",
    "Spanish": "Español",
    "Standings": "Clasificación",
    "Summary": "Resumen",
    "There are no active competitions. Create or join a competition to start tracking matches, standings and stats.": "No hay competiciones activas. Crea o únete a una competición para empezar a registrar partidos, clasificaciones y estadísticas.",
    "This competition is in single elimination mode.": "Esta competición está en modo eliminación directa.",
    "To start tracking matches, standings and stats, complete your profile.": "Para empezar a registrar partidos, clasificaciones y estadísticas, completa tu perfil.",
    "Type": "Tipo",
    "Universal sports platform": "Plataforma deportiva universal",
    "View details": "Ver detalles",
    "View or manage matches": "Ver o gestionar partidos",
    "Warning: this tournament has a maximum of 11 points per set. Please check the points entered.": "Atención: este torneo tiene un máximo de 11 puntos por set. Comprueba los puntos introducidos.",
    "Wins": "Victorias",
    "Yes": "Sí",
    "here": "aquí",
    "set": "set",
    "player": "jugador",
    "of": "de",
    "Other": "Otros",
    "PT": "PT",
    "WR%": "WR%",
    "VS": "VS",
    "Pts": "Pts",
    "Join a competition": "Únete a una competición",
    "Join an existing competition to start tracking matches, standings and stats.": "Únete a una competición existente para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Join an existing competition to start recording matches, rankings, and statistics.": "Únete a una competición existente para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Create a new competition to start tracking matches, standings and stats.": "Crea una nueva competición para empezar a registrar partidos, clasificaciones y estadísticas.",
    "Join an existing competition": "Únete a una competición existente",
    "Confirm your password": "Confirma tu contraseña",
    "Join an existing competition <br> with the <strong>code</strong> provided by your organizer <br> or competition member": "Únete a una competición existente <br> con el <strong>código</strong> facilitado por tu organizador <br> o miembro de la competición",
    "Join": "Únete",
    "Ask for the code, it's located in the 'Organizer's competitions' tab": "Pide el código; se encuentra en la pestaña «Competiciones del organizador».",
    "Fill in all required fields": "Rellena todos los campos obligatorios.",
    "Error deleting competition. Please try again later.": "Error al eliminar la competición. Inténtalo de nuevo más tarde.",
    "Invalid credentials. Please try again.": "Credenciales no válidas. Inténtalo de nuevo.",
    "Your email address has not been confirmed. Check your inbox for the confirmation link.": "Tu dirección de correo electrónico no ha sido confirmada. Revisa tu bandeja de entrada para encontrar el enlace de confirmación.",
    "Join or create another competition": "Únete o crea otra competición",
    "Organizer controlled, only the admin adds matches and results.  ": "Controlado por el organizador; solo el admin añade partidos y resultados.  ",
    "Self managed, all participants can add matches freely.": "Autogestionado: todos los participantes pueden añadir partidos libremente.",
    "Keep track of points during the match with a tap or with your voice": "Controla los puntos durante el partido con un toque o con tu voz.",
    "Add a match manually by entering the players and the final score": "Añade un partido manualmente introduciendo a los jugadores y el marcador final.",
    "Record points live during the match, start by selecting players.": "Registra los puntos en directo durante el partido; empieza seleccionando a los jugadores.",
    "Click here if you want to participate in the competition you are creating. This way you will be a player in the tournament.": "Haz clic aquí si quieres participar en la competición que estás creando. Así formarás parte del torneo como jugador.",
    "Are you sure?": "¿Estás seguro?",
    "Are you sure you want to delete the player?": "¿Estás seguro de que quieres eliminar al jugador?",
    "Are you sure you want to delete the competition?": "¿Estás seguro de que quieres eliminar la competición?",
    "Define your format": "Define tu formato",
    "Pick groups, single elimination or mixed formats, set scoring rules and spin up your lobby in a few clicks.": "Elige liguillas, eliminación directa o formatos mixtos, define las reglas de puntuación y prepara tu lobby en unos clics.",
    "Invite players and staff, register sign-ups, assign tables and keep everyone in sync with notifications and live bracket.": "Invita a jugadores y staff, registra inscripciones, asigna mesas y mantén a todos sincronizados con notificaciones y cuadro en directo.",
    "Monitor and tell the story": "Supervisa y cuenta la historia",
    "Log sets in real time, update automatic leaderboards and publish shareable reports with detailed statistics.": "Registra los sets en tiempo real, actualiza clasificaciones automáticas y publica informes compartibles con estadísticas detalladas.",
    "Open your tournament": "Abre tu torneo",
    "Try the live demo": "Prueba la demo en vivo",
    "Access analytics": "Accede a las analíticas",
    "Ready to transform your next competition?": "¿Listo para transformar tu próxima competición?",
    "Of course, you can set palettes, logos...": "Por supuesto, puedes definir paletas, logotipos...",
    "Access the platform": "Accede a la plataforma",
    "Request a guided demo": "Solicita una demo guiada",
    "Create group or knockout tournaments, customize rules and let the platform handle schedules and rankings.": "Crea torneos de liguilla o eliminatorios, personaliza las reglas y deja que la plataforma gestione calendarios y clasificaciones.",
    "Update results and live stats, synchronized across all your team or club devices.": "Actualiza resultados y estadísticas en directo, sincronizados en todos los dispositivos de tu equipo o club.",
    "Analyze performance, identify player trends and prepare upcoming challenges with visual reports and smart analytics.": "Analiza el rendimiento, identifica tendencias de los jugadores y prepara los próximos desafíos con informes visuales y analíticas inteligentes.",
    "Organize, manage and share your tournaments with": "Organiza, gestiona y comparte tus torneos con",
    "Forget WhatsApp groups and messy spreadsheets. Create stunning, automatic, professional tournaments in seconds.": "Olvídate de los grupos de WhatsApp y de las hojas de cálculo desordenadas. Crea en segundos torneos espectaculares, automáticos y profesionales.",
    "Learn more": "Saber más",
    "Try now": "Pruébalo ahora",
    "Everything you need for a perfect tournament": "Todo lo que necesitas para un torneo perfecto",
    "Sport Board automates everything others make you do manually — and makes you look good doing it.": "Sport Board automatiza todo lo que los demás te obligan a hacer manualmente y te hace quedar genial haciéndolo.",
    "More organized. More beautiful. Easier.": "Más organizado. Más bonito. Más fácil.",
    "Complete your profile": "Completa tu perfil",
    "To start tracking matches, standings and stats, complete your profile.": "Para empezar a registrar partidos, clasificaciones y estadísticas, completa tu perfil.",
    "Choose whether to start a new competition or join an existing one.": "Elige si quieres iniciar una nueva competición o unirte a una existente.",
}

manual_de = {
    "Add match": "Spiel hinzufügen",
    "Add players": "Spieler hinzufügen",
    "Add set points": "Satzpunkte hinzufügen",
    "Add competition": "Wettbewerb hinzufügen",
    "Add": "Hinzufügen",
    "Add player": "Spieler hinzufügen",
    "Add players manually": "Spieler manuell hinzufügen",
    "Add points live": "Punkte live hinzufügen",
    "Add user": "Benutzer hinzufügen",
    "Add a match manually by entering the players and the final score": "Füge ein Spiel manuell hinzu, indem du die Spieler und das Endergebnis eingibst",
    "Add players one by one by entering their nickname. (Irreversible).": "Füge die Spieler einzeln hinzu, indem du ihren Spitznamen eingibst. (Unumkehrbar).",
    "Auto-updating": "Automatische Aktualisierung",
    "Automatic rankings and schedules": "Automatische Tabellen und Spielpläne",
    "Best of": "Best-of",
    "Bracket": "Turnierbaum",
    "Cancel": "Abbrechen",
    "Champion": "Champion",
    "Close": "Schließen",
    "Code copied to clipboard!": "Code in die Zwischenablage kopiert!",
    "Competition code": "Wettbewerbscode",
    "Competition deleted successfully.": "Wettbewerb erfolgreich gelöscht.",
    "Competition details": "Wettbewerbsdetails",
    "Competition name": "Name des Wettbewerbs",
    "Competitions": "Wettbewerbe",
    "Continue": "Fortfahren",
    "Create": "Erstellen",
    "Create a competition": "Einen Wettbewerb erstellen",
    "Create a free account...": "Erstelle ein kostenloses Konto...",
    "Create a new competition": "Einen neuen Wettbewerb erstellen",
    "Create a new competition to start recording matches, rankings, and statistics.": "Erstelle einen neuen Wettbewerb, um Spiele, Ranglisten und Statistiken zu erfassen.",
    "Create a new competition to start tracking matches, standings and stats.": "Erstelle einen neuen Wettbewerb, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "Create free account": "Kostenloses Konto erstellen",
    "Create or join a competition": "Erstelle oder tritt einem Wettbewerb bei",
    "Create your first competition": "Erstelle deinen ersten Wettbewerb",
    "Create your tournament": "Erstelle dein Turnier",
    "Created by": "Erstellt von",
    "Delete": "Löschen",
    "Delete player": "Spieler löschen",
    "Details": "Details",
    "Do you want to join the competition as a player?": "Möchtest du dem Wettbewerb als Spieler beitreten?",
    "Email is used to send match notifications directly to the player. Enter it to send tournament updates. You can also leave it blank.": "E-Mail wird verwendet, um Spielbenachrichtigungen direkt an den Spieler zu senden. Gib sie ein, um Turnier-Updates zu verschicken. Du kannst das Feld auch leer lassen.",
    "Elimination mode is under development: soon you will record matches and automatic advancements.": "Der Eliminationsmodus befindet sich in Entwicklung: Bald kannst du Spiele und automatische Fortschritte erfassen.",
    "English": "Englisch",
    "Enter your email": "Gib deine E-Mail ein",
    "Enter your password": "Gib dein Passwort ein",
    "Free management": "Freie Verwaltung",
    "Group": "Gruppe",
    "Group stage": "Gruppenphase",
    "Here you can add multiple players at once, enter a nickname (and an optional photo) and click 'Add player' to add him.": "Hier kannst du mehrere Spieler auf einmal hinzufügen: Gib einen Spitznamen (und optional ein Foto) ein und klicke auf „Spieler hinzufügen“.",
    "Home": "Startseite",
    "Loading...": "Wird geladen...",
    "Log in": "Anmelden",
    "Log in with Google": "Mit Google anmelden",
    "Sign up with Google": "Mit Google registrieren",
    "Log Out": "Abmelden",
    "No matches found, add one!": "Keine Spiele gefunden, füge eines hinzu!",
    "No competitions yet. Create your first competition to start tracking matches, standings and stats.": "Noch keine Wettbewerbe. Erstelle deinen ersten Wettbewerb, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "No players yet. Add the first players to start tracking matches, standings and stats.": "Noch keine Spieler. Füge die ersten Spieler hinzu, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "Or sign up": "Oder registriere dich",
    "Profile": "Profil",
    "Edit your nickname": "Bearbeite deinen Spitznamen",
    "Reset points": "Punkte zurücksetzen",
    "Save Match": "Spiel speichern",
    "Save set": "Satz speichern",
    "Search player": "Spieler suchen",
    "Select a player": "Spieler auswählen",
    "Semifinals": "Halbfinale",
    "Send access link by email": "Zugangslink per E-Mail senden",
    "Send access link to your friends via email to allow them to join the competition.": "Sende deinen Freunden den Zugangslink per E-Mail, damit sie dem Wettbewerb beitreten können.",
    "Invite your friends to join the competition via email.": "Lade deine Freunde per E-Mail zur Teilnahme am Wettbewerb ein.",
    "Set a date": "Datum festlegen",
    "Sets (best of)": "Sätze (Best of)",
    "Share the invitation code with your friends to allow them to join the competition and start recording matches, <br> click here to copy it to the clipboard.": "Teile den Einladungscode mit deinen Freunden, damit sie dem Wettbewerb beitreten und mit dem Erfassen der Spiele beginnen können. <br> Klicke hier, um ihn in die Zwischenablage zu kopieren.",
    "Share this code with your friends to allow them to join the competition.": "Teile diesen Code mit deinen Freunden, damit sie dem Wettbewerb beitreten können.",
    "Single elimination": "K.-o.-Modus",
    "Single elimination bracket, lose and you are out.": "K.-o.-Baum – eine Niederlage bedeutet das Aus.",
    "Some modes, like single elimination or group stage with knockout, require admin management. Go back and select Admin management to create them.": "Einige Modi, etwa der K.-o.-Modus oder eine Gruppenphase mit Finalrunde, erfordern die Verwaltung durch den Organisator. Gehe zurück und wähle die Admin-Verwaltung, um sie zu erstellen.",
    "Spanish": "Spanisch",
    "Standings": "Tabelle",
    "Summary": "Übersicht",
    "There are no active competitions. Create or join a competition to start tracking matches, standings and stats.": "Es gibt keine aktiven Wettbewerbe. Erstelle einen Wettbewerb oder tritt einem bei, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "This competition is in single elimination mode.": "Dieser Wettbewerb findet im K.-o.-Modus statt.",
    "To start tracking matches, standings and stats, complete your profile.": "Um Spiele, Tabellen und Statistiken zu verfolgen, vervollständige dein Profil.",
    "Type": "Typ",
    "Universal sports platform": "Universelle Sportplattform",
    "View details": "Details anzeigen",
    "View or manage matches": "Spiele ansehen oder verwalten",
    "Warning: this tournament has a maximum of 11 points per set. Please check the points entered.": "Achtung: Dieses Turnier erlaubt maximal 11 Punkte pro Satz. Bitte überprüfe die eingegebenen Punkte.",
    "Wins": "Siege",
    "Yes": "Ja",
    "here": "hier",
    "set": "Satz",
    "player": "Spieler",
    "of": "von",
    "Other": "Andere",
    "PT": "PT",
    "WR%": "WR%",
    "VS": "VS",
    "Pts": "Pts",
    "Join a competition": "Einem Wettbewerb beitreten",
    "Join an existing competition to start tracking matches, standings and stats.": "Tritt einem bestehenden Wettbewerb bei, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "Join an existing competition to start recording matches, rankings, and statistics.": "Tritt einem bestehenden Wettbewerb bei, um Spiele, Ranglisten und Statistiken zu erfassen.",
    "Create a new competition to start tracking matches, standings and stats.": "Erstelle einen neuen Wettbewerb, um Spiele, Tabellen und Statistiken zu verfolgen.",
    "Join an existing competition": "Tritt einem bestehenden Wettbewerb bei",
    "Confirm your password": "Bestätige dein Passwort",
    "Join an existing competition <br> with the <strong>code</strong> provided by your organizer <br> or competition member": "Tritt einem bestehenden Wettbewerb <br> mit dem <strong>Code</strong> bei, den du von deinem Organisator <br> oder einem Wettbewerbsmitglied erhalten hast.",
    "Join": "Beitreten",
    "Ask for the code, it's located in the 'Organizer's competitions' tab": "Frag nach dem Code – er befindet sich im Tab „Wettbewerbe des Organisators“.",
    "Fill in all required fields": "Fülle alle Pflichtfelder aus.",
    "Error deleting competition. Please try again later.": "Fehler beim Löschen des Wettbewerbs. Bitte versuche es später erneut.",
    "Invalid credentials. Please try again.": "Ungültige Anmeldedaten. Bitte versuche es erneut.",
    "Your email address has not been confirmed. Check your inbox for the confirmation link.": "Deine E-Mail-Adresse wurde nicht bestätigt. Überprüfe deinen Posteingang nach dem Bestätigungslink.",
    "Keep track of points during the match with a tap or with your voice": "Verfolge die Punkte während des Spiels mit einem Tipp oder mit deiner Stimme.",
    "Add a match manually by entering the players and the final score": "Füge ein Spiel manuell hinzu, indem du die Spieler und das Endergebnis eingibst.",
    "Record points live during the match, start by selecting players.": "Erfasse die Punkte live während des Spiels, indem du zuerst die Spieler auswählst.",
    "Click here if you want to participate in the competition you are creating. This way you will be a player in the tournament.": "Klicke hier, wenn du am Wettbewerb teilnehmen möchtest, den du erstellst. So spielst du beim Turnier mit.",
    "Select match management mode": "Wähle den Spielverwaltungsmodus",
    "Choose management type": "Wähle den Verwaltungstyp",
    "Join or create another competition": "Tritt einem weiteren Wettbewerb bei oder erstelle einen neuen",
    "Organizer controlled, only the admin adds matches and results.  ": "Vom Veranstalter gesteuert; nur der Admin trägt Spiele und Ergebnisse ein.  ",
    "Self managed, all participants can add matches freely.": "Selbstverwaltet: Alle Teilnehmenden können Spiele frei hinzufügen.",
    "Define your format": "Lege dein Format fest",
    "Pick groups, single elimination or mixed formats, set scoring rules and spin up your lobby in a few clicks.": "Wähle Gruppen-, K.-o.- oder Mischformate, lege die Punkteregeln fest und richte deine Lobby mit wenigen Klicks ein.",
    "Invite players and staff, register sign-ups, assign tables and keep everyone in sync with notifications and live bracket.": "Lade Spieler und Staff ein, registriere Anmeldungen, weise Tische zu und halte alle mit Benachrichtigungen und Live-Bracket auf dem Laufenden.",
    "Monitor and tell the story": "Beobachte und erzähle die Geschichte",
    "Log sets in real time, update automatic leaderboards and publish shareable reports with detailed statistics.": "Protokolliere Sätze in Echtzeit, aktualisiere automatische Ranglisten und veröffentliche teilbare Berichte mit detaillierten Statistiken.",
    "Open your tournament": "Starte dein Turnier",
    "Try the live demo": "Probiere die Live-Demo aus",
    "Access analytics": "Greife auf Analysen zu",
    "Ready to transform your next competition?": "Bist du bereit, deinen nächsten Wettbewerb zu verändern?",
    "Of course, you can set palettes, logos...": "Natürlich kannst du Paletten, Logos ... festlegen.",
    "Access the platform": "Greif auf die Plattform zu",
    "Request a guided demo": "Fordere eine geführte Demo an",
    "Create group or knockout tournaments, customize rules and let the platform handle schedules and rankings.": "Erstelle Gruppen- oder K.-o.-Turniere, passe die Regeln an und überlass der Plattform Spielpläne und Tabellen.",
    "Update results and live stats, synchronized across all your team or club devices.": "Aktualisiere Ergebnisse und Live-Statistiken, synchronisiert auf allen Geräten deines Teams oder Clubs.",
    "Analyze performance, identify player trends and prepare upcoming challenges with visual reports and smart analytics.": "Analysiere Leistungen, erkenne Spielertrends und bereite kommende Herausforderungen mit visuellen Berichten und smarten Analysen vor.",
    "Organize, manage and share your tournaments with": "Organisiere, verwalte und teile deine Turniere mit",
    "Forget WhatsApp groups and messy spreadsheets. Create stunning, automatic, professional tournaments in seconds.": "Vergiss WhatsApp-Gruppen und chaotische Tabellen. Erstelle in Sekunden beeindruckende, automatische Profiturniere.",
    "Learn more": "Mehr erfahren",
    "Try now": "Probiere es jetzt aus",
    "Everything you need for a perfect tournament": "Alles, was du für ein perfektes Turnier brauchst",
    "Sport Board automates everything others make you do manually — and makes you look good doing it.": "Sport Board automatisiert alles, was andere dich manuell erledigen lassen – und sorgt dafür, dass du dabei gut aussiehst.",
    "More organized. More beautiful. Easier.": "Besser organisiert. Schöner. Einfacher.",
    "Complete your profile": "Vervollständige dein Profil",
    "To start tracking matches, standings and stats, complete your profile.": "Um Spiele, Tabellen und Statistiken zu verfolgen, vervollständige dein Profil.",
    "Choose whether to start a new competition or join an existing one.": "Wähle, ob du einen neuen Wettbewerb startest oder einem bestehenden beitrittst.",
    "Join a competition": "Einem Wettbewerb beitreten",
    "Are you sure you want to delete the player?": "Bist du sicher, dass du den Spieler löschen möchtest?",
    "Are you sure you want to delete the competition?": "Bist du sicher, dass du den Wettbewerb löschen möchtest?",
}


def translate_batch(texts, target):
    if not texts:
        return []
    joined = "\n".join(texts)
    params = {
        'client': 'gtx',
        'sl': 'en',
        'tl': target,
        'dt': 't',
        'q': joined,
    }
    response = requests.get(API_URL, params=params, timeout=10)
    response.raise_for_status()
    data = response.json()
    translated_joined = ''.join(part[0] for part in data[0])
    lines = translated_joined.split('\n')
    if len(lines) > len(texts):
        lines = lines[:len(texts)]
    if len(lines) != len(texts):
        raise ValueError(f"Unexpected translation count: expected {len(texts)}, got {len(lines)}")
    return lines


def postprocess_es(text: str) -> str:
    replacements = {
        'coincidencia': 'partido',
        'coincidencias': 'partidos',
        'Competencia': 'Competición',
        'competencia': 'competición',
        'Competencias': 'Competiciones',
        'competencias': 'competiciones',
        'Agregar': 'Añadir',
        'agregar': 'añadir',
        'Agrega': 'Añade',
        'agrega': 'añade',
        'ajuste': 'set',
        'Ajuste': 'Set',
        'ajustes': 'sets',
        'Ajustes': 'Sets',
        'Haga clic': 'Haz clic',
        'Haga': 'Haz',
        'Únase': 'Únete',
        'Regístrese': 'Regístrate',
        'grabar partidos': 'registrar partidos',
        'grabarás': 'registrarás',
        'pronto registrarás': 'pronto podrás registrar',
        'competiciónes': 'competiciones',
        'competicións': 'competiciones',
        'Eliminación única': 'Eliminación directa',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def postprocess_de(text: str) -> str:
    replacements = [
        ('Fügen Sie', 'Füge'),
        ('Geben Sie', 'Gib'),
        ('Klicken Sie', 'Klicke'),
        ('Teilen Sie', 'Teile'),
        ('Sie können', 'Du kannst'),
        ('Sie musst', 'Du musst'),
        ('Sie müssen', 'Du musst'),
        ('Sie kannst', 'Du kannst'),
        ('Sie möchtest', 'Du möchtest'),
        (' Sie.', ' du.'),
        (' Sie,', ' du,'),
        (' Sie!', ' du!'),
        (' Sie?', ' du?'),
        ('Sie ', 'du '),
        ('Ihre ', 'deine '),
        ('Ihren ', 'deinen '),
        ('Ihrem ', 'deinem '),
        ('Ihrer ', 'deiner '),
        ('Ihr ', 'dein '),
        ('Ihnen', 'dir'),
        ('Competition', 'Wettbewerb'),
        ('Livepunkte', 'Live-Punkte'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text

with open('public/lang.json', encoding='utf-8') as f:
    data = json.load(f)

unique_en = sorted({value.get('en') for value in data.values() if value.get('en')})
cache_es = {}
cache_de = {}

index = 0
while index < len(unique_en):
    batch = unique_en[index:index + BATCH_SIZE]
    missing_es = [text for text in batch if text not in manual_es]
    missing_de = [text for text in batch if text not in manual_de]

    if missing_es:
        es_translations = translate_batch(missing_es, 'es')
        for original, translated in zip(missing_es, es_translations):
            cache_es[original] = postprocess_es(translated)
    if missing_de:
        de_translations = translate_batch(missing_de, 'de')
        for original, translated in zip(missing_de, de_translations):
            cache_de[original] = postprocess_de(translated)

    for text in batch:
        if text in manual_es:
            cache_es[text] = manual_es[text]
        if text in manual_de:
            cache_de[text] = manual_de[text]

    index += BATCH_SIZE

for value in data.values():
    en = value.get('en')
    if not en:
        continue
    value['es'] = cache_es[en]
    value['de'] = cache_de[en]

with open('public/lang.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
